apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-replica-set
  labels:
      app: guess-ask-reddit
      type: backend
spec:
  template: # each section of the template is a pod
    metadata:
      name: backend
      labels:
        lang: go
        tier: backend
    spec:
      containers:
        - name: backend
          image: harrisonwaffel/guess-ask-reddit-backend:v1
          env:
            - name: DATABASE_HOST
              value: "database"
            - name: DATABASE_PORT
              value: "5432"
            - name: DEPLOY_MODE
              value: "k8s"
  replicas: 2
  selector:
    matchLabels:
      lang: go
      tier: backend
